spring.application.name=cdc-api

spring.jackson.date-format=dd-MM-yyyy

spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/petshop?useTimezone=true&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3306/petshop?&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
spring.datasource.url=jdbc:mysql://localhost:3306/livraria?connectionTimeZone=America/Sao_Paulo
spring.datasource.username=root
#spring.datasource.password=123
spring.datasource.password=root

# Mudar o caminho do Swagger UI
springdoc.swagger-ui.path=/livraria-api
# Mudar o caminho do JSON da API
springdoc.api-docs.path=/docs


